### ISSUE TITLE
Unable to locate visualsearch.model file

### ISSUE THREAD

**Issue by OElesin** [ThomasDelteil/VisualSearch_MXNet#6]
The model server configuration references a file `visualsearch.model`. However, I could not locate the file. I also tried to recreate it but could not.

Kindly explain more on this thanks

**Comment by OElesin** [comment]
I eventually found that the `model-archiver` for this. However, the model server fails to start. Outputs the following error messages below:

```bash
2019-01-03 01:42:29,828 [INFO ] W-9000-visual_search_test-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - Traceback (most recent call last):
2019-01-03 01:42:29,828 [INFO ] W-9000-visual_search_test-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle -   File "/Users/XXXXXXX/Library/Python/2.7/lib/python/site-packages/mms/model_service_worker.py", line 167, in <module>
2019-01-03 01:42:29,828 [INFO ] W-9000-visual_search_test-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle -     worker.run_server()
2019-01-03 01:42:29,828 [INFO ] W-9000-visual_search_test-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle -   File "/Users/XXXXXXX/Library/Python/2.7/lib/python/site-packages/mms/model_service_worker.py", line 150, in run_server
2019-01-03 01:42:29,828 [INFO ] W-9001-visual_search_test-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - Backend worker process die.
2019-01-03 01:42:29,828 [INFO ] W-9000-visual_search_test-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle -     self.handle_connection(cl_socket)
2019-01-03 01:42:29,828 [INFO ] W-9001-visual_search_test-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - Traceback (most recent call last):
2019-01-03 01:42:29,828 [INFO ] W-9000-visual_search_test-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle -   File "/Users/XXXXXXX/Library/Python/2.7/lib/python/site-packages/mms/model_service_worker.py", line 116, in handle_connection
2019-01-03 01:42:29,829 [INFO ] W-9001-visual_search_test-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle -   File "/Users/XXXXXXX/Library/Python/2.7/lib/python/site-packages/mms/model_service_worker.py", line 167, in <module>
2019-01-03 01:42:29,829 [INFO ] KQueueEventLoopGroup-4-4 com.amazonaws.ml.mms.wlm.WorkerThread - 9000 Worker disconnected. WORKER_STARTED
2019-01-03 01:42:29,829 [INFO ] W-9000-visual_search_test-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle -     service, result, code = self.load_model(msg)
2019-01-03 01:42:29,829 [INFO ] W-9001-visual_search_test-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle -     worker.run_server()
2019-01-03 01:42:29,829 [INFO ] W-9001-visual_search_test-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle -   File "/Users/XXXXXXX/Library/Python/2.7/lib/python/site-packages/mms/model_service_worker.py", line 150, in run_server
2019-01-03 01:42:29,829 [INFO ] W-9001-visual_search_test-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle -     self.handle_connection(cl_socket)
2019-01-03 01:42:29,829 [INFO ] W-9001-visual_search_test-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle -   File "/Users/XXXXXXX/Library/Python/2.7/lib/python/site-packages/mms/model_service_worker.py", line 116, in handle_connection
2019-01-03 01:42:29,829 [INFO ] W-9000-visual_search_test-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle -   File "/Users/XXXXXXX/Library/Python/2.7/lib/python/site-packages/mms/model_service_worker.py", line 96, in load_model
2019-01-03 01:42:29,829 [INFO ] W-9001-visual_search_test-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle -     service, result, code = self.load_model(msg)
2019-01-03 01:42:29,829 [DEBUG] W-9000-visual_search_test com.amazonaws.ml.mms.wlm.WorkerThread - Backend worker monitoring thread interrupted or backend worker process died.
java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2088)
	at java.util.concurrent.ArrayBlockingQueue.poll(ArrayBlockingQueue.java:418)
	at com.amazonaws.ml.mms.wlm.WorkerThread.run(WorkerThread.java:139)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Can you please help? @ThomasDelteil

**Comment by ThomasDelteil** [comment]
Hi @OElesin, I'll have a look after the holiday period, thanks for reporting this.

**Comment by ThomasDelteil** [comment]
I see that you found the bug that I reported on the MMS repo, to fix it you can indeed just rename the service file to something else.
